[package]
name = "lun"
version = "0.0.1"
authors = ["McKayla Washburn <mckayla@hey.com>"]
edition = "2018"
description = "A virtual machine designed to run Lun Machine-code"

default-run = "lun"

[dependencies]
num_enum = "0.5.1"
