name: main

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-rs:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                rust-version: [stable, beta, nightly]
            fail-fast: false

        steps:
            - uses: actions/checkout@v2

            - run: rustup default ${{ matrix.rust-version }}

            - run: rustc -V
            - run: cargo -V

            - run: rustup component add rustfmt
              if: matrix.rust-version == 'stable'
            - run: rustup component add clippy
              if: matrix.rust-version == 'stable'

            - run: cargo fmt -- --check
              if: matrix.rust-version == 'stable'
            - run: cargo clippy
              if: matrix.rust-version == 'stable'

            - run: cargo build --verbose
            - run: cargo test --verbose
